# fly.toml app configuration file generated for hurve on 2025-08-25T17:13:26+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hurve'
primary_region = 'lhr'

[http_service]
  internal_port = 9160
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
